// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

func LoginPage(csrf_token string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><title>Login | BookBits Editor</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><script src=\"/static/bundle-main.js\"></script><script src=\"/static/bundle-packages.js\" defer></script></head><body x-data=\"{}\" hx-get=\"/\" hx-trigger=\"session-setup\"><div class=\"w-full h-screen flex flex-col justify-center items-center\" x-data=\"{}\"><div class=\"flex flex-col items-center max-w-sm bg-white border rounded-lg shadow-sm p-12 border-neutral-200/60 w-[60%]\"><h5 class=\"text-2xl font-medium leading-none tracking-tight text-neutral-900\">Log In to your Account</h5><p x-ref=\"loginErrMsg\" class=\"text-sm font-light text-red-400 mt-4\"></p><form @htmx:before-send=\"\n				$refs.loginBtn.innerHTML=&#39;Logging In...&#39;\n				$refs.loginBtn.disabled = true\n				\" @htmx:before-on-load=\"\n				$refs.loginBtn.innerHTML=&#39;Log Me In&#39;\n				$refs.loginBtn.disabled = false\n				\" @htmx:after-on-load=\"\n					mainBundle.setupSession($event.detail.xhr)\n				\" @htmx:response-error.window=\"$refs.loginErrMsg.innerHTML = mainBundle.handleLoginError($event.detail.xhr)\" id=\"login-form\" class=\"mt-8 flex flex-col space-y-5 w-full p-0\" hx-post=\"/login\" hx-target=\"this\" hx-swap=\"none\" hx-headers=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(
			fmt.Sprintf("{\"X-CSRF-Token\":\"%s\"}", csrf_token))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/views/login_page.templ`, Line: 33, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div class=\"w-full max-w-xs mx-auto\"><input name=\"user-email\" type=\"email\" placeholder=\"Email Address\" onkeyup=\"this.setCustomValidity(&#39;&#39;)\" hx-on:htmx:validation:validate=\"if (this.value.length == &#39;&#39;) {\n						this.setCustomValidity(&#39;Please enter an email address.&#39;)\n						htmx.find(&#39;#login-form&#39;).reportValidity()\n					}\" class=\"flex w-full h-10 px-3 py-6 text-sm bg-white border rounded-md border-neutral-300 ring-offset-background placeholder:text-neutral-500 focus:border-neutral-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-400 disabled:cursor-not-allowed disabled:opacity-50\"></div><div class=\"w-full max-w-xs mx-auto\"><input name=\"user-password\" type=\"password\" placeholder=\"Password\" onkeyup=\"this.setCustomValidity(&#39;&#39;)\" hx-on:htmx:validation:validate=\"if (this.value.length == &#39;&#39;) {\n						this.setCustomValidity(&#39;Please enter a password.&#39;)\n						htmx.find(&#39;#login-form&#39;).reportValidity()\n					}\" class=\"flex w-full h-10 px-3 py-6 text-sm bg-white border rounded-md border-neutral-300 ring-offset-background placeholder:text-neutral-500 focus:border-neutral-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-neutral-400 disabled:cursor-not-allowed disabled:opacity-50\"></div><button x-ref=\"loginBtn\" type=\"submit\" class=\"inline-flex w-full items-center justify-center px-4 py-3 text-sm font-medium tracking-wide text-white transition-colors duration-200 bg-blue-600 rounded-md hover:bg-blue-700 disabled:bg-neutral-300 focus:ring-2 focus:ring-offset-2 focus:ring-blue-700 focus:shadow-outline focus:outline-none\">Log Me In</button></form><p class=\"text-sm font-light mt-8\">Facing Issue? <span class=\"text-blue-600\">Contact Admin</span></p></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
